### ISSUE TITLE
All shortcut for IOTHIDDENMENU 

### ISSUE THREAD

**Issue by Ryjun0** [wr3cckl3ss1/system_shell_2#2]
am start com.sec.hiddenmenu/.Program_Edit

ENTER THE DRAGON

am start -n com.sec.hiddenmenu/.IOTHiddenMenu -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.KOREA_Mode -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.KoreaMode_Prevail -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.SerialPort -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.ItsOnMenu -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.ServiceModeApp -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Test -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PhoneUtil -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OTATest -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.LTE -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.FIELDTESTMODE -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.HiddenMenuEnable -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.GlobalHiddenMenuEnable -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BSRMaxStage_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BSRMaxTimer_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BSRTimer_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BSR_Clear -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band25MIMO_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band41MIMO_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BandPriorityEdit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Bsr_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DL256QAM_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DNS_Set -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DOtoLTECustomScan_edit

am start -n com.sec.hiddenmenu/.DebugingMenu -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Direct_Connect -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Feature_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Feature_Option -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.File_view -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.GlmsSettings -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.HomeOrg_VoiceSO_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Home_SID_NID_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.LTEHDRScanInterval_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.LTE_available_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MEIDInfo -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MaxScanTime_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.NR_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.NabSettings -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.NextLTE_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OneXPSDormancy_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OneXToLTEHandup_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PciEarfcnLock_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Prevail2TestMode -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Program_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Program_Opt -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.RESET -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.SMSFormat -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.SMSoIP_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.ServiceModeApp -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.ServiceModeApp_D2PP -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Sms_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.SprintMenu -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.TM9FDD_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.TM9TDD_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.TerminalMode -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.UL64QAM_edit -e 7267864872 72678647376477466
 
am start -n com.sec.hiddenmenu/.VoLTE_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Voice_SoSetting -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Voice_SoSetting_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.data_edit_Bsr -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.oneXPSActiveDuration_edit -e 7267864872 72678647376477466

ABC - > XYZ

DATA
am start -n com.sec.hiddenmenu/.AKEY2 -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.AKEY2_Vzw -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.AKEY2_via -e 7267864872 72678647376477466

APN Native Conection
am start -n com.sec.hiddenmenu/.APNActiveConnection -e 7267864872 72678647376477466

Advanced
am start -n com.sec.hiddenmenu/.Advanced -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Advanced1x -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Advanced_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Advanced_View -e 7267864872 72678647376477466

ASM Debug UI
am start -n com.sec.hiddenmenu/.Asmdebug -e 7267864872 72678647376477466

Band Class 10
am start -n com.sec.hiddenmenu/.BC10_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BC10_View -e 7267864872 72678647376477466

Talk Back
am start -n com.sec.hiddenmenu/.BLV -e 7267864872 72678647376477466

BRAND
am start -n com.sec.hiddenmenu/.BRAND -e 7267864872 72678647376477466

BSR Max Stage
am start -n com.sec.hiddenmenu/.BSRMaxStage_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BSRMaxStage_view -e 7267864872 72678647376477466

BSR Max Timer
am start -n com.sec.hiddenmenu/.BSRMaxTimer_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BSRMaxTimer_view -e 7267864872 72678647376477466

BSR Timer
am start -n com.sec.hiddenmenu/.BSTimer_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.BSRTimer_view -e 7267864872 72678647376477466

Clear LTE Available File
am start -n com.sec.hiddenmenu/.BSR_Clear -e 7267864872 72678647376477466

Band 25 MIMO
am start -n com.sec.hiddenmenu/.Band25MIMO_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band25MIMO_view -e 7267864872 72678647376477466

Band 25 Enable
am start -n com.sec.hiddenmenu/.Band25_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band25_View -e 7267864872 72678647376477466

Band 26 Enable
am start -n com.sec.hiddenmenu/.Band26_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band26_View -e 7267864872 72678647376477466

Band 3 Enable
am start -n com.sec.hiddenmenu/.Band3_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band3_View -e 7267864872 72678647376477466

Band 41 MIMO
am start -n com.sec.hiddenmenu/.Band41MIMO_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band41MIMO_view -e 7267864872 72678647376477466

Band 41 PCII
am start -n com.sec.hiddenmenu/.Band41PCII_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band41PCII_View -e 7267864872 72678647376477466

Band 41 Tx Switch
am start -n com.sec.hiddenmenu/.Band41TxSwitch_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band41TxSwitch_View -e 7267864872 72678647376477466

Band 41 Enable
am start -n com.sec.hiddenmenu/.Band41_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Band41_View -e 7267864872 72678647376477466

Band Priority Edit
am start -n com.sec.hiddenmenu/.BandPriority -e 7267864872 72678647376477466

CA Enabled 
am start -n com.sec.hiddenmenu/.CAEnabled_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.CAEnabled_Edit_9CA -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.CAEnabled_Edit_no3CA -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.CAEnabled_View -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.CAEnabled_View_9CA -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.CAEnabled_View_no3CA -e 7267864872 72678647376477466

Clear Reset
am start -n com.sec.hiddenmenu/.CLEAR_Reset -e 7267864872 72678647376477466

CTN
am start -n com.sec.hiddenmenu/.CTN -e 7267864872 72678647376477466

DEBUG MENU
am start -n com.sec.hiddenmenu/.DEBUGMENU -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DEBUGMENU_D2PP -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DEBUGMENU_GAUDI -e 7267864872 72678647376477466

DL256QAM
am start -n com.sec.hiddenmenu/.DL256QAM_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DL256QAM_view -e 7267864872 72678647376477466

DNS Set
am start -n com.sec.hiddenmenu/.DNS_Set -e 7267864872 72678647376477466

DO to LTE Custom Scan
am start -n com.sec.hiddenmenu/.DOtoLTECustomScan_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DOtoLTECustomScan_view -e 7267864872 72678647376477466

DSA
am start -n com.sec.hiddenmenu/.DSA_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DSA_View -e 7267864872 72678647376477466

DSS Option
am start -n com.sec.hiddenmenu/.DSSOption -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DSSOption_View -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DSS_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DSS_View -e 7267864872 72678647376477466

DTMF Set
am start -n com.sec.hiddenmenu/.DTMF_Set -e 7267864872 72678647376477466

DUN
am start -n com.sec.hiddenmenu/.DUN -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DUN_vzw -e 7267864872 72678647376477466

Data Profile
am start -n com.sec.hiddenmenu/.Dataprofile_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Dataprofile_View -e 7267864872 72678647376477466

Debug Menu
am start -n com.sec.hiddenmenu/.DebugMenu_Check -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.DebugMenu -e 7267864872 72678647376477466

Direct Connect
am start -n com.sec.hiddenmenu/.Direct_Connect -e 7267864872 72678647376477466

DM Mode
am start -n com.sec.hiddenmenu/.DmMode -e 7267864872 72678647376477466

EHRPD
am start -n com.sec.hiddenmenu/.EHRPD_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.EHRPD_View -e 7267864872 72678647376477466

EVDO
am start -n com.sec.hiddenmenu/.EVDO_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.EVDO_View -e 7267864872 72678647376477466

EVRC - B
am start -n com.sec.hiddenmenu/.EVRCB_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.EVRCB_View -e 7267864872 72678647376477466

FIELD TEST MODE
am start -n com.sec.hiddenmenu/.FIELDTESTMODE -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.FIELDTESTMODE_View -e 7267864872 72678647376477466

Feature 
am start -n com.sec.hiddenmenu/.Feature_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Feature_Option -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Feature_View -e 7267864872 72678647376477466

View LTE Available File 
am start -n com.sec.hiddenmenu/.File_view -e 7267864872 72678647376477466

GPSCLRX 
am start -n com.sec.hiddenmenu/.GPSCLRX -e 7267864872 72678647376477466

GLMS Setting 
am start -n com.sec.hiddenmenu/.GlmsSettings -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.GlmsSettings_View -e 7267864872 72678647376477466

Global Hidden Menu Enable /Disable
am start -n com.sec.hiddenmenu/.GlobalHiddenMenuEnable -e 7267864872 72678647376477466

HDR1X
am start -n com.sec.hiddenmenu/.HDR1X_Selection -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.HDR1X_Selection2 -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.HDR1X_Selection_C1vzw -e 7267864872 72678647376477466

Others
am start -n com.sec.hiddenmenu/.Hdata_edit_others -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Hdata_others -e 7267864872 72678647376477466

Hidden Menu Enable / Disable
am start -n com.sec.hiddenmenu/.HiddenMenuEnable -e 7267864872 72678647376477466

Home Org Voice SO
am start -n com.sec.hiddenmenu/.HomeOrg_VoiceSO_Edit -e 7267864872 72678647376477466

Home Page Voice SO
am start -n com.sec.hiddenmenu/.HomePage_VoiceSO_Edit -e 7267864872 72678647376477466

Home SID NID
am start -n com.sec.hiddenmenu/.Home_SID_NID_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Home_SID_NID_View -e 7267864872 72678647376477466

IMS
am start -n com.sec.hiddenmenu/.IMS_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.IMS_View -e 7267864872 72678647376477466

IOTHiddenMenu
am start -n com.sec.hiddenmenu/.IOTHiddenMenu -e 7267864872 72678647376477466

Its On Menu
am start -n com.sec.hiddenmenu/.ItsOnMenu -e 7267864872 72678647376477466

KOREA - SPRINT - INDIA MENU
am start -n com.sec.hiddenmenu/.KOREA_Mode -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.KoreaMode_Prevail -e 7267864872 72678647376477466

LTE
am start -n com.sec.hiddenmenu/.LTE -e 7267864872 72678647376477466

LTE HDR Scan Interval
am start -n com.sec.hiddenmenu/.LTEHDRScanInterval_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.LTEHDRScanInterval_view -e 7267864872 72678647376477466

LTE Mode
am start -n com.sec.hiddenmenu/.LTEMode -e 7267864872 72678647376477466

LTE Roaming
am start -n com.sec.hiddenmenu/.LTERoaming_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.LTERoaming_View -e 7267864872 72678647376477466

LTE Enable 
am start -n com.sec.hiddenmenu/.LTE_Edit -e 7267864872 72678647376477466

LTE Specitic Parameters
am start -n com.sec.hiddenmenu/.LTE_Parameters -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.LTE_Parameters_View -e 7267864872 72678647376477466

LTE Status
am start -n com.sec.hiddenmenu/.LTE_View -e 7267864872 72678647376477466

LTE Available 
am start -n com.sec.hiddenmenu/.LTE_available_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.LTE_available_view -e 7267864872 72678647376477466

LTE Enable 
am start -n com.sec.hiddenmenu/.LTE_ed -e 7267864872 72678647376477466

ME ID info
am start -n com.sec.hiddenmenu/.MEIDInfo -e 7267864872 72678647376477466

MMS
am start -n com.sec.hiddenmenu/.MMSActivity -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSC -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSC_Proxy -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSC_Proxy_Port -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSC_Proxy_Port_View -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSC_Proxy_View -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSC_view -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSCinfo -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MMSCinfo_edit -e 7267864872 72678647376477466

MRD
am start -n com.sec.hiddenmenu/.MRD -e 7267864872 72678647376477466

MSL Option
Service Programming 
am start -n com.sec.hiddenmenu/.MSLOption_Cham -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_Checker -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_NamEdit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_NamEdit_ChamLeon -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_NamEdit_via -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_NamView -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_NamView_ChamLeon -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_NamView_via -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MSL_option -e 7267864872 72678647376477466

Max Scan Time
am start -n com.sec.hiddenmenu/.MaxScanTime_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.MaxScanTime_view -e 7267864872 72678647376477466

Multimedia 
am start -n com.sec.hiddenmenu/.Multimedia_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Multimedia_View -e 7267864872 72678647376477466

NR5G
am start -n com.sec.hiddenmenu/.NR_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.NR_View -e 7267864872 72678647376477466

NAB
am start -n com.sec.hiddenmenu/.NabSettings -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.NabSettings_View -e 7267864872 72678647376477466

NamBlock
am start -n com.sec.hiddenmenu/.NamBlock -e 7267864872 72678647376477466

Next LTE
am start -n com.sec.hiddenmenu/.NextLTE_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.NextLTE_view -e 7267864872 72678647376477466

OTA Test
am start -n com.sec.hiddenmenu/.OTASP -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OTATest -e 7267864872 72678647376477466

OTKSL
am start -n com.sec.hiddenmenu/.OTKSL -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OTKSL2 -e 7267864872 72678647376477466

One XToLTE
am start -n com.sec.hiddenmenu/.OneXPSDormancy_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OneXPSDormancy_view -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OneXToLTEHandup_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.OneXToLTEHandup_view -e 7267864872 72678647376477466

Others
am start -n com.sec.hiddenmenu/.Others -e 7267864872 72678647376477466

Pci Ear fcn Lock
am start -n com.sec.hiddenmenu/.PciEarfcnLock_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PciEarfcnLock_view -e 7267864872 72678647376477466

PhoneUtil 
am start -n com.sec.hiddenmenu/.PhoneUtil -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PhoneUtil_C1vzw -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PhoneUtil_Gaudi -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PhoneUtil_Icon -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PhoneUtil_Jspr -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.PhoneUtil_Prevail2SPR -e 7267864872 72678647376477466

Port map
am start -n com.sec.hiddenmenu/.Port_Map -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Prevail2TestMode -e 7267864872 72678647376477466

PRL Write
am start -n com.sec.hiddenmenu/.Pri_Write -e 7267864872 72678647376477466

Program Menu
am start -n com.sec.hiddenmenu/.ProgramMenu -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Program_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Program_Opt -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Program_View -e 7267864872 72678647376477466

RC DATA
am start -n com.sec.hiddenmenu/.RC_DATA -e 7267864872 72678647376477466

RESET
am start -n com.sec.hiddenmenu/.RESET -e 7267864872 72678647376477466

RTN
am start -n com.sec.hiddenmenu/.RTN_Reset_Gaudi -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.RTN_View -e 7267864872 72678647376477466

RoamOrg VoiceSO
am start -n com.sec.hiddenmenu/.RoamOrg_VoiceSO_Edit -e 7267864872 72678647376477466

SCRTN
am start -n com.sec.hiddenmenu/.SCRTN -e 7267864872 72678647376477466

SDC Registration
am start -n com.sec.hiddenmenu/.SDC_Registration -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.SDC_Registration_View -e 7267864872 72678647376477466

SMS FORMAT 
am start -n com.sec.hiddenmenu/.SMSFormat-e 7267864872 72678647376477466

SMS oIP
am start -n com.sec.hiddenmenu/.SMSoIP_edit -e 7267864872 72678647376477466

SO73 COP 0
am start -n com.sec.hiddenmenu/.SO73COP0 -e 7267864872 72678647376477466

SO73 COP 17
am start -n com.sec.hiddenmenu/.SO73COP17 -e 7267864872 72678647376477466

Serial Menu
am start -n com.sec.hiddenmenu/.SerialMode -e 7267864872 72678647376477466

Serial Enable 
am start -n com.sec.hiddenmenu/.SerialPort -e 7267864872 72678647376477466

ServiceModeApp
am start -n com.sec.hiddenmenu/.ServiceModeApp -e 7267864872 72678647376477466

ServiceModeApp_D2PP
am start -n com.sec.hiddenmenu/.ServiceModeApp_D2PP -e 7267864872 72678647376477466

SmartDockSetting
am start -n com.sec.hiddenmenu/.SmartDockSetting -e 7267864872 72678647376477466

SmartdockMMDSetting
am start -n com.sec.hiddenmenu/.SmartdockMMDSetting -e 7267864872 72678647376477466

SMS Setting
am start -n com.sec.hiddenmenu/.Sms_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Sms_View -e 7267864872 72678647376477466

Sprit Menu
am start -n com.sec.hiddenmenu/.SprintMenu -e 7267864872 72678647376477466

FDD TM9
am start -n com.sec.hiddenmenu/.TM9FDD_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.TM9FDD_view -e 7267864872 72678647376477466

TDD TM9
am start -n com.sec.hiddenmenu/.TM9TDD_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.TM9TDD_view -e 7267864872 72678647376477466

TTY
am start -n com.sec.hiddenmenu/.TTY -e 7267864872 72678647376477466

Teles Pree
am start -n com.sec.hiddenmenu/.TelesPree_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.TelesPree_Option -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.TelesPree_View -e 7267864872 72678647376477466

Teminal Mode
am start -n com.sec.hiddenmenu/.TerminalMode -e 7267864872 72678647376477466

Test
am start -n com.sec.hiddenmenu/.Test -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Test_Edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Test_View -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Test_cri -e 7267864872 72678647376477466

Toggle NAI
am start -n com.sec.hiddenmenu/.Toggle_NAI -e 7267864872 72678647376477466

Tool Launcher Enabler
am start -n com.sec.hiddenmenu/.ToolLauncherEnabler -e 7267864872 72678647376477466

64QAM
am start -n com.sec.hiddenmenu/.UL64QAM_edit -e 7267864872 72678647376477466
 
am start -n com.sec.hiddenmenu/.UL64QAM_view -e 7267864872 72678647376477466

USBChargeMenu
am start -n com.sec.hiddenmenu/.USBChargeMenu -e 7267864872 72678647376477466

VoLTE
am start -n com.sec.hiddenmenu/.VoLTE_edit -e 7267864872 72678647376477466

Voice Privacy
am start -n com.sec.hiddenmenu/.VoicePrivacy -e 7267864872 72678647376477466

Voice SOS Setting 
am start -n com.sec.hiddenmenu/.Voice_SoSetting -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.Voice_SoSetting_Edit -e 7267864872 72678647376477466

WiMAX Menu
am start -n com.sec.hiddenmenu/.WiMAX_Menu -e 7267864872 72678647376477466

DATA
am start -n com.sec.hiddenmenu/.data_edit_Bsr -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.editgateway1 -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.hdata -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.hdata_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.hdata_options -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.hdata_view_Bsr -e 7267864872 72678647376477466

one XPS Active Duration
am start -n com.sec.hiddenmenu/.oneXPSActiveDuration_edit -e 7267864872 72678647376477466

am start -n com.sec.hiddenmenu/.oneXPSActiveDuration_view -e 7267864872 72678647376477466

Browser
am start -n com.sec.hiddenmenu/.viewgateway1 -e 7267864872 72678647376477466

**Comment by wr3cckl3ss** [comment]
Sorry for the late response. As much as you may want or need  the buttons. This project is done on my behalf. As I am focused on new projects. As I stated, I was challenged to add more buttons to SMT Shell and I did. So I challenge you to add more to either my version or to BluFeNiX. If your smart enough  to figure some out, then  I have faith you can figure out how to add more.
