### ISSUE TITLE
Question - Galaxy Note 10 April 2023 Update

### ISSUE THREAD

**Issue by marek26340** [wr3cckl3ss1/system_shell_2#3]
Hello.

Really appreciate your work. All of you, your work is awesome!
Can I ask you if it is safe for me to update my phone to the April 2023 patch level?
AFAIK the build date is on April 3rd according to this page: https://samfw.com/firmware/SM-N970F/XEZ/N970FXXS8HWC3 
(there's a couple more pages with this firmware with quite confusing info, like openfirmware says it was build on March 28th...)
And when I read a previous issue, you have said that the patch was included into AOSP in around the 2nd week of that month?

All I want to know is if I really should stay on the January 2023 firmware, or if it is safe for me to upgrade to this April firmware without losing system shell access, which I use for band/cell locking quite often.
The July update is around the corner, so I want to know if I can update my phone atleast to April patches, since there was a ton of security holes.

Thank you for your time and help!

P.S. If I will lose access, I REALLY don't want to downgrade and lose all of my data. I mean, I do have a backup in Smart Switch, but a factory reset of my phone would also mean resetting my Galaxy Watch 4. I also applied a lot of "secret" settings directly into the settings database and my phone is also debloated. It'll certainly take me a long time to get everything back up and running...

**Comment by wr3cckl3ss** [comment]
It's really on you to decide. April was the month of the announcement and there is no real date to define when any changes were actually made or implemented. Worst scenario, you can just start over new and reapply your secret settings. Best case, if the firmware you flash is not patched and now your good, at least for a little while. Good luck.

**Comment by marek26340** [comment]
Okay, so I've bit the bullet and tried it. The actual build date of my firmware turned out to be 28th march. 
SMT Shell works perfectly fine. Thanks for your help and hopefully my info will help someone else with similar questions!
