### ISSUE TITLE
got it working :)

### ISSUE THREAD

**Issue by CamsShaft** [wr3cckl3ss1/system_shell_2#5]
Finally got something awesome to work on my crapdragon s10 thanks to you! I went into this expecting the same as always, conflcts with compatibility or just samsung being samsung. I havent attempted anything on my S22 and not sure if theres even anything worthwhile to try (expensive phone=expensive!). Thanks a lot for your hard work!

**Comment by wr3cckl3ss** [comment]
Thanks. But this project is old now. And the real core of it. Doesn't belong to me but to BLuFeNiX. He is owed all the credit here. 

As for your second question, I kindly ask you to look at my other repos. You might like what you see. Good luck.

**Comment by CamsShaft** [comment]
Sick! I was going to check out your repos but had to come here first of course. As for it being old, so is my nigh indestructible phone. I have no idea how it's not dead after everything I've done to it. I'll check out BLuFeNiX too and give my thanks. Some of us were meant to reap the rewards while others worked their asses off on things we can't comprehend. That's how it is with coding and myself unfortunately, wish I could contribute more besides the odd bug fix suggestion or an "I'm not worthy note" haha. Have a good one!

**Comment by wr3cckl3ss** [comment]
I'm definitely not a coder. I dont even read source. And can barely comprehend the most basic of things....I'm definitely new here and still have a lot to learn. Start small and sooner or later....you'll get better. Just stay persistent.

**Comment by CamsShaft** [comment]
Hey man, not sure where else to write about relevant things so I'm here for now (discord? telegram? pornhub??) Anyways, I'm probably writing for no reason but I thought I'd better name drop anyways. IF you haven't already, you should definitely check out an app called Inure (app.simple.inure). It's got tons of great features and is probably the best app manager I've ever used. It's updated like once a month, has a pretty decent terminal that utilizes your favourite thing in the world, Shizuku of course, and I have no idea what other things have probably gone over my head. I've barely scratched the surface. I think this would make a great addition to your collection and believe it could work well with the other goodies you already have. Have a great Friday/weekend and let me know if theres a different place for this stuff so your page doesnt get too polluted.

**Comment by wr3cckl3ss** [comment]
Write to me on telegram @
 t.me/wr3cckl3ss
